'''
Created on Apr 7, 2014

@author: JWShumaker
Problem ID 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

# Again, let's make this a function
# Note that our fib series begins with 1 and 2 and that sum begins at 2
def SumEvenFibs(max, term1 = 1, term2 = 2, sum = 2):    
    # Now we loop until our second term EXCEEDS the max
    while(term2 <= max):           
        # This iterates our fibonacci sequence
        # Note that the PREVIOUS value of term1 is used in calculating the assignment
        #     for term2                 
        term1, term2 = term2, term1 + term2
        
        # We add the new term to our sum iff it is divisible by 2  
        if not term2 % 2:
            sum += term2
    
    return sum

print(SumEvenFibs(4000000))
